CREATE TABLE [dbo].[2018_Full_Tickets_Audit]
(
[event_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[section_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[row_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seat_num] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_seat_num] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num_seats] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acct_id] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owner_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[price_code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[class_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qualifier_state_names] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[purchase_price] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block_purchase_price] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[full_price] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block_full_price] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ticket_type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ticket_type_category] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reserved_ind] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reserved_desc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reserved_datetime] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[release_datetime] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hold_source] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[retail_ticket_type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[retail_qualifiers] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[retail_mask] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[retail_price_level] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_plan_event_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comp] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seat Type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC Ticket Type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Event Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[joinerB] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acct_type_desc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SG Price] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paid] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_event_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add_datetime] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
